maxbet = 100
minjackbot = 500
wikiurl = 'https://github.com/SpiceBot/SpiceBot/wiki/Casino'
deck = [2, 3, 4, 5, 6, 7, 8, 9, 10, 'J', 'Q', 'K', 'A']*4
lotterymax = 30
slotwheel = ['MODEM', 'BSOD', 'RAM', 'CPU', 'RAID', 'VLANS', 'PATCH', 'WIFI', 'CPU', 'CLOUD', 'VLANS', 'AI', 'DARKWEB', 'BLOCKCHAIN', 'PASSWORD']
slottimeout = 5
colors = ['red', 'black']
roulettetimeout = 25
maxwheel = 29
keyword = 'BSOD'
